name: Publish ds-auth to k8s staging
on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    name: Build, Test and Publish to DO K8s
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Authenticate kubectl
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ds-k8s
      - name: Inject additional config
        run: "printf \"${{ secrets.STG_DEPLOY_PROPERTIES }}\" >> ./src/main/resources/application.properties"
      - name: Build/Deploy
        run: mvn clean package -Dquarkus.kubernetes.deploy=true